sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.16.1

services:
  - docker

before_install:
  - docker pull docker/whalesay

script:
  - docker-compose -f docker-compose.yml up -d
  - docker-compose -f docker-compose.yml ps
