sudo: required

language: generic
services:
  - docker

before_install:
  - docker pull segence/hadoop

script:
  - docker-compose up -d
  - docker ps
  - docker exec --user hadoop hadoop-namenode /bin/sh -c "yes Y|/home/hadoop/utils/format-namenode.sh"
  - docker exec hadoop-namenode /bin/sh -c "service hadoop start"
  - docker exec --user root hadoop-namenode /bin/sh -c "/usr/local/spark/sbin/start-master.sh"
  - echo "Done with driver's machine..."
  - docker exec --user root hadoop-datanode1 /bin/sh -c "/usr/local/spark/sbin/start-slave.sh spark://172.18.0.2:7077"
  - docker exec --user hadoop hadoop-datanode1 /bin/sh -c "cd;/home/hadoop/utils/run-wordcount.sh"
#  - docker exec --user hadoop hadoop-datanode1 /bin/sh -c "/home/hadoop/utils/run-wordcount.sh"
#  - docker exec --user hadoop hadoop-datanode1 /bin/sh -c "pwd"
#  - docker exec --user hadoop hadoop-datanode1 /bin/sh -c "whoami"
