sudo: required

language: generic
services:
  - docker

before_install:
  - docker pull segence/hadoop

script:
  - docker-compose up -d
  - docker ps
  - ls
  - docker exec hadoop-namenode bash
