sudo: required

language: generic
services:
  - docker

before_install:
  - docker pull segence/hadoop

script:
  - docker-compose up -d
  - docker ps
  - docker exec --user hadoop hadoop-namenode /bin/sh -c "yes Y|/home/hadoop/utils/format-namenode.sh"
  - docker exec hadoop-namenode /bin/sh -c "service hadoop start"
  - docker exec --user root hadoop-namenode /bin/sh -c "/usr/local/spark/sbin/start-master.sh"
  - docker exec --user hadoop hadoop-namenode /bin/sh -c "cat /usr/local/spark/logs/spark--org.apache.spark.deploy.master.Master-1-hadoop-namenode.out"
  - echo "Done with driver's machine..."
  - docker exec --user root hadoop-datanode1 /bin/sh -c "/usr/local/spark/sbin/start-slave.sh spark://172.18.0.2:7077"
  #- docker exec --user hadoop hadoop-datanode1 /bin/sh -c "cat /usr/local/spark/logs/spark--org.apache.spark.deploy.worker.Worker-1-hadoop-datanode1.out"
  - docker exec --user hadoop hadoop-datanode1 /bin/sh -c "cat /usr/local/spark/logs/*.*|grep Success"
