sudo: required

language: generic
services:
  - docker

before_install:
  - docker pull segence/hadoop

script:
  - docker-compose up -d
  - docker ps
  - docker exec hadoop-namenode /bin/sh -c "yes Y|/home/hadoop/utils/format-namenode.sh"
  - ls -R
